sudo: false
language: python
cache: pip
python:
  - 3.5
  - 3.6
  - 3.7-dev
env:
  TOXENV=py

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=coverage
    - python: 3.6
      env: TOXENV=lint

install:
  - pip install --upgrade pip
  - pip install -rrequirements_dev.txt

script:
  - tox

after_success:
- if [[ $TOXENV == "py" ]]; then tox -e codecov; fi
