build: false  # Not a C# project
environment:
  matrix:
    - PYTHON: "C:\\Python35"
      TOXENV: py35
    - PYTHON: "C:\\Python36"
      TOXENV: py36
    - PYTHON: "C:\\Python37"
      TOXENV: py37
matrix:
  fast_finish: true

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -m pip install --upgrade pip"
  - "python -m pip install -r requirements_dev.txt"

test_script:
  - "python -m tox"

cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '%USERPROFILE%\.cache\pre-commit'
